// default values by scalar variable
export const default_scalar_values = [
  {
    mode: 'ocean',
    var_name: 'temp',
    var_name_kor: '수온',
    min: 0,
    max: 35,
    scheme: 'Blues',
    title: '수온(°C)',
    tickFormat: '.0f',
  },
  {
    mode: 'ocean',
    var_name: 'salt',
    var_name_kor: '염분',
    min: 0,
    max: 35,
    scheme: 'Inferno',
    title: '염분(psu)',
    tickFormat: '.0f',
  },
  {
    mode: 'ocean',
    var_name: 'zeta',
    var_name_kor: '해수면',
    min: -1,
    max: 1,
    scheme: 'Plasma',
    title: '해수면(m)',
    tickFormat: '.1f',
  },
  {
    mode: 'ocean',
    var_name: 'spd',
    var_name_kor: '유속',
    min: 0,
    max: 3,
    scheme: 'Cool',
    title: '유속(m/s)',
    tickFormat: '.1f',
  },
  {
    mode: 'wave',
    var_name: 'hsig',
    var_name_kor: '파고',
    min: 0,
    max: 10,
    scheme: 'Turbo',
    title: '유의파고(m)',
    tickFormat: '.0f',
  },
  {
    mode: 'wave',
    var_name: 'rpeak',
    var_name_kor: '파주기',
    min: 0,
    max: 5,
    scheme: 'Viridis',
    title: '파주기(s)',
    tickFormat: '.0f',
  },
  {
    mode: 'air',
    var_name: 'pair',
    var_name_kor: '기압',
    min: 950,
    max: 1100,
    scheme: 'Viridis',
    title: '기압(Pa)',
    tickFormat: '.0f',
  },
  {
    mode: 'air',
    var_name: 'tair',
    var_name_kor: '기온',
    min: -20,
    max: 40,
    scheme: 'Turbo',
    title: '기온(K)',
    tickFormat: '.0f',
  },
  {
    mode: 'air',
    var_name: 'rh',
    var_name_kor: '습도',
    min: 0,
    max: 100,
    scheme: 'Viridis',
    title: '습도(%)',
    tickFormat: '+%',
  },
];

// color schemes
export const color_schemes = [
  'Blues',
  'Cividis',
  'Cool',
  'GnBu',
  'Greens',
  'Inferno',
  'Magma',
  'Oranges',
  'OrRd',
  'Plasma',
  'Purples',
  'Reds',
  'Turbo',
  'Viridis',
  'Warm',
  'YlGn',
  'YlGnBu',
  'YlOrRd',
];

// earth radius in meter
export const EARTH_RADIUS_METERS = 6.3e6;
